name: Build Executables
on: [push]
jobs:

  build-win:
    name: Build Windows binary
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Build Windows exe
      working-directory: cmd/game
      shell: bash
      run: go build -o ../../slapTrax.exe
    - name: Upload Windows exe
      uses: actions/upload-artifact@v4
      with:
        name: slapTrax-win
        path: |
          LICENSE.md
          slapTrax.exe

  build-mac:
    name: Build MacOS binary
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Build Mac exe
      working-directory: cmd/game
      shell: bash
      run: go build -o ../../slapTrax
    - name: Tar it up
      shell: bash
      run: tar -zcvf slapTrax-mac.tar.gz slapTrax LICENSE.md
    - name: Upload Mac exe
      uses: actions/upload-artifact@v4
      with:
        name: slapTrax-mac
        path: slapTrax-mac.tar.gz

  build-lin:
    name: Build Linux binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Install dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get -y install libgl1-mesa-dev xorg-dev libasound2-dev
    - name: Build Linux exe
      working-directory: cmd/game
      shell: bash
      run: go build -o ../../slapTrax
    - name: Tar it up
      shell: bash
      run: tar -zcvf slapTrax-lin.tar.gz slapTrax LICENSE.md
    - name: Upload Linux exe
      uses: actions/upload-artifact@v4
      with:
        name: slapTrax-lin
        path: slapTrax-lin.tar.gz

  build-web:
    name: Build Web binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Build Web binary
      working-directory: cmd/game
      shell: bash
      run: GOOS=js GOARCH=wasm go build -o ../../web/slapTrax.wasm
    - name: Copy WASM exec script
      shell: bash
      run: cp $(go env GOROOT)/misc/wasm/wasm_exec.js web/.
    - name: Upload Web build
      uses: actions/upload-artifact@v4
      with:
        name: slapTrax-web
        path: |
          web/
          LICENSE.md

  upload-bundle:
    name: Bundle binaries with dev assets
    runs-on: ubuntu-latest
    needs: [build-lin, build-mac, build-win]
    steps:
    - uses: actions/checkout@v4
    - name: Download Windows binary
      uses: actions/download-artifact@v4
      with:
        name: slapTrax-win
    - name: Download Linux binary
      uses: actions/download-artifact@v4
      with:
        name: slapTrax-lin
    - name: Download Mac binary
      uses: actions/download-artifact@v4
      with:
        name: slapTrax-mac
    - name: Upload beta testing bundle
      uses: actions/upload-artifact@v4
      with:
        name: slapTrax-bundle
        path: |
          README.md
          LICENSE.md
          slapTrax-lin.tar.gz
          slapTrax-mac.tar.gz
          slapTrax.exe

  deploy-win:
    name: Deploy Windows build to itch.io
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: build-win
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: slapTrax-win
    - uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: windows
        ITCH_GAME: slaptrax
        ITCH_USER: liqmix
        PACKAGE: slapTrax.exe
        VERSION: ${{github.ref_name}}

  deploy-mac:
    name: Deploy MacOs build to itch.io
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: build-mac
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: slapTrax-mac
    - name: Extract tarball
      shell: bash
      run: tar -zxvf slapTrax-mac.tar.gz
    - uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: mac
        ITCH_GAME: slaptrax
        ITCH_USER: liqmix
        PACKAGE: slapTrax
        VERSION: ${{github.ref_name}}

  deploy-lin:
    name: Deploy Linux build to itch.io
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: build-lin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: slapTrax-lin
    - name: Extract tarball
      shell: bash
      run: tar -zxvf slapTrax-lin.tar.gz
    - uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: linux
        ITCH_GAME: slaptrax
        ITCH_USER: liqmix
        PACKAGE: slapTrax
        VERSION: ${{github.ref_name}}

  deploy-web:
    name: Deploy Web build to itch.io
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: build-web
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: slapTrax-web
    - uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: web
        ITCH_GAME: slaptrax
        ITCH_USER: liqmix
        PACKAGE: web
        VERSION: ${{github.ref_name}}